basePath: /
definitions:
  routes.securityDummyWebhook.payload:
    properties:
      new_ip:
        example: 10.0.0.1:80085
        type: string
      old_ip:
        example: 127.0.0.1:80085
        type: string
      user_agent:
        example: useragent/10.1.1
        type: string
      user_guid:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
  routes.whoami.resp:
    properties:
      GUID:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
info:
  contact:
    email: gorropand@gmail.com
    name: Artem Darizhapov
  description: JWT Authentication Assignment API
  title: Authentication JWT API
  version: "1.0"
paths:
  /auth/{guid}/login:
    post:
      description: Issues a pair of authentication tokens and sets them as cookies
      parameters:
      - description: A valid user GUID
        example: 123e4567-e89b-12d3-a456-426614174000
        in: path
        name: guid
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid GUID
        "500":
          description: Internal Server Error
      summary: Login user
      tags:
      - auth
  /auth/{guid}/logout:
    post:
      description: Deauthorizes client. If they are not authenticated nothing happens.
      parameters:
      - description: A valid user GUID
        example: 123e4567-e89b-12d3-a456-426614174000
        in: path
        name: guid
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Logout user
      tags:
      - auth
  /auth/{guid}/refresh:
    post:
      description: |-
        Refreshes access and refresh tokens if the refresh token is valid.
        Deauthorizes user if the user agent does not match to the one that issued the refresh token.
      parameters:
      - description: A valid user GUID
        example: 123e4567-e89b-12d3-a456-426614174000
        in: path
        name: guid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Refresh tokens
      tags:
      - auth
  /security/refresh-new-ip:
    post:
      consumes:
      - application/json
      description: Demo endpoint for a "refresh from new IP" action notifications
      parameters:
      - description: Notification payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/routes.securityDummyWebhook.payload'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Security notification webhook
      tags:
      - security
  /whoami:
    get:
      description: Returns authenticated user GUID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.whoami.resp'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get current user's GUID
      tags:
      - user
swagger: "2.0"
